config/routes.rb
Rails.application.routes.draw do


  resources :cities, :only => [:index] do
    resources :neighborhoods, :only => [:index]
  end

  resources :activities, :only => [:index] do
    resources :genres, :only => [:index]
  end

  resources :matches, :only => [:index, :show, :update, :new, :create]
  resources :venues, :only => [:index, :show, :create]

  resources :imports, :only => [:index]
  root to: 'website#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  has_many :genres
  # has_many :matches, through: :genres

end

app/models/city.rb
class City < ActiveRecord::Base

  has_many :neighborhoods
  # has_many :matches, through: :neighborhoods

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  belongs_to :activity
  has_many :matches

end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :neighborhood
  belongs_to :genre
  belongs_to :venue
  # belongs_to :activity, through: :genres
  # belongs_to :city, through: :neighborhoods

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base

  belongs_to :city
  has_many :matches

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  has_many :matches

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  require 'json'

  def index
    @cities = City.all.order(:id)
    render :json => @cities, status: 200
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    if params[:activity_id]
      @genres = Genre.where(activity_id: params[:activity_id]).order(:name)
    else
      @genres = Genre.all.order(:name)
    end

    render :json => @genres, status: 200
  end

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  def index
    @matches = Match.all.order(:neighborhood_id).order(:genre_id)
    render :layout => 'imports'
  end



end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.all.order(:id)
    render :json => @matches, status: 200
  end

  def show
    if params["genre"] && params["neighborhood"]
      requested_genre_id = params["genre"]
      requested_neighborhood_id = params["neighborhood"]

      @matches = Match.where("neighborhood_id = ? AND genre_id = ?", requested_neighborhood_id, requested_genre_id)
      p "MATCHES: #{@matches}"

      if @matches.length == 0
        match_to_send = {name: "Hmmm we haven't found a good option there yet", link: "https://www.google.com/", id: 0}
      elsif @matches.length > 1
        random_index = rand(@matches.length)
        match_to_send = @matches[random_index]
      else
        match_to_send = @matches.first
      end

      p "MATCH TO SEND"
      p match_to_send
      if match_to_send[:id] == 0
        render json: match_to_send, status: 200
      else
        venue_to_send = Venue.find(match_to_send.venue_id)
        render json: venue_to_send, status: 200
      end
    else
      p "NO GENRE OR NEIGHBORHOOD"
    end
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to '/imports'
    else
      render 'new'
    end
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      if @match.save
        redirect_to '/imports'
      else
        p "DIDN'T SAVE"
      end
    else
      p "DIDN'T UPDATE"
    end
  end

  private

    def match_params
      params.require(:match).permit(:venue_id, :neighborhood_id, :genre_id)
    end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index

    @venues = Venue.all.order(:id)
    render :json => @venues, status: 200

  end

  def show
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.new(venue_params)
      if @venue.save
        redirect_to @venue
      else
        p "NOT SAVED ERROR"
      end
  end

  private
    def venue_params
      params.require(:venue).permit(:name, :link, :address, :city, :state, :zip_code)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/imports_helper.rb
module ImportsHelper

  def get_venue(venue_id)
    Venue.find(venue_id)
  end

  def get_neighborhood(venue_id)
    Neighborhood.find(venue_id)
  end

  def get_genre(venue_id)
    Genre.find(venue_id)
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>i wanna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/imports.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <title>i wanna</title>
  <%= csrf_meta_tags %>
  <link href="../../../assets/imports.css" rel="stylesheet" type="text/css">
  <link href="../../../assets/bootstrap.min.css" rel="stylesheet" type="text/css">
  <script src="../../../assets/jquery-1.11.0.min.js"></script>
  <script src="../../../assets/imports.js"></script>


  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div>
  <h1 class="import-header">CREATE NEW MATCH</h1>
  <%= form_for :match, url: matches_path do |f| %>
    <%= f.text_field :neighborhood_id, :placeholder => "Neighborhood ID" %>
    <%= f.text_field :genre_id, :placeholder => "Genre ID"%>
    <%= f.text_field :venue_id, :placeholder => "Venue ID" %>
    <%= f.submit 'Create' %>
  <% end %>
</div>
<div>
  <h1 class="import-header">CREATE NEW VENUE</h1>
  <%= form_for :venue, url: venues_path do |f| %>
    <%= f.text_field :name, :placeholder => "name" %>
    <%= f.text_field :link, :placeholder => "link"%>
    <%= f.text_field :address, :placeholder => "address" %>
    <%= f.text_field :city, :placeholder => "city" %>
    <%= f.text_field :state, :placeholder => "state" %>
    <%= f.text_field :zip_code, :placeholder => "zip_code" %>
    <%= f.submit 'Create' %>
  <% end %>
</div>
<div class="all-matches">
  <h1 class="import-header">ALL MATCHES</h1>
  <div>
    <table>
      <thead>
        <tr class="row">
          <th class="col-lrg-1 import-table-headers">Match ID</th>
          <th class="col-lrg-2 import-table-headers">Neighborhood ID</th>
          <th class="col-lrg-2 import-table-headers">Neighborhood</th>
          <th class="col-lrg-1 import-table-headers">Genre ID</th>
          <th class="col-lrg-2 import-table-headers">Genre</th>
          <th class="col-lrg-2 import-table-headers">Venue ID</th>
          <th class="col-lrg-2 import-table-headers">Name</th>
          <th class="col-lrg-2 import-table-headers">Update</th>
          <tr>
      </thead>
      <tbody class="import-details">
        <% @matches.each do |match|%>
          <tr id="<%= match.id %>" class="row">
          <%= form_for match do |f| %>
            <td class="col-lrg-1 match-link"><%= match.id %></td>
            <td class="col-lrg-1 match-link"><%= match.neighborhood_id %></td>
            <td class="col-lrg-2 match-link"><%= get_neighborhood(match.neighborhood_id).name %></td>
            <td class="col-lrg-1 match-link"><%= match.genre_id %></td>
            <td class="col-lrg-2 match-link"><%= get_genre(match.genre_id).name %></td>
            <td class="col-lrg-1"><%= f.text_field :venue_id, :class => 'import-text-box' %></td>
            <td class="col-lrg-2 match-link"><%= get_venue(match.venue_id).name %></td>
            <td class="col-lrg-2 import-buttons"><%= f.submit 'Update', :class => 'approve-delete-buttons update-button', :id => match.id %></td>
          <% end %>

        </tr>
        <% end %>
      </tbody>
    <table>
  </div>
</div>
</body>
</html>

app/views/layouts/website-old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>i wanna</title>

  <!-- Bootstrap Core CSS -->
  <link href="../../../assets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="../../../assets/landing-page.css" rel="stylesheet">
  <link href="../../../assets/app.css" rel="stylesheet">
  <script src="../../../assets/jquery-1.11.0.min.js"></script>
  <script src="../../../assets/app.js"></script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63385529-1', 'auto');
  ga('send', 'pageview');

</script>

  <!-- Custom Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
</head>
<body class="background-image">

  <div class="intro-header">
      <div class="container">
          <div class="row">
                <div id="hero" class="static-header light clearfix">
                  <div class="text-heading">
                      <h1 class="animated hiding" data-animation="bounceInDown" data-delay="0"><span class="highlight">i wanna</span></h1>
                      <p class="animated hiding" data-animation="fadeInDown" data-delay="500">Discover the best restaurants and bars in the San Francisco Bay Area without being overwhelmed by hundreds of options.</p>
                      <p><a class="contact-link" href="mailto:contact@yeahiwanna.com">Get in touch.</a></p>
                      <ul class="list-inline">
                      </ul>
                  </div>
              </div>
          </div>
      </div>
      <!-- /.container -->
  </div>
  <!-- /.intro-header -->

</body>

    <script type="text/javascript" src="../../../assets/bootstrap.min.js"></script>

</html>

app/views/layouts/website.html.erb
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title>i wanna</title>
    <meta name="description" content="Startups template">
    <meta name="keywords" content="Startups template">
    <link rel="shortcut icon" href="../../../assets/app_icon.png">
    <link rel="apple-touch-icon" href="../../../assets/app_icon.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../../../assets/app_icon.png">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="../../../assets/bootstrap.min.css" type="text/css" media="all" />
    <link rel="stylesheet" href="../../../assets/font-awesome.min.css" type="text/css" media="all" />
    <link rel="stylesheet" href="../../../assets/font-lineicons.css" type="text/css" media="all" />
    <link rel="stylesheet" href="../../../assets/animate.css" type="text/css" media="all" />
    <link rel="stylesheet" href="../../../assets/toastr.min.css" type="text/css" media="all" />
    <link rel="stylesheet" href="../../../assets/style.css" type="text/css" media="all" />

</head>

<body id="landing-page">

    <!-- Preloader -->
    <div id="mask">
        <div id="loader"></div>
    </div>

    <header>
        <nav class="navigation navigation-header">
            <div class="container">
                <div class="navigation-brand">
                    <button class="navigation-toggle visible-xs" type="button" data-toggle="dropdown" data-target=".navigation-navbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navigation-navbar">
                    <ul class="navigation-bar navigation-bar-left">
                        <li class="active"><a href="#hero">Home</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                    <ul class="navigation-bar navigation-bar-right">
                        <li class="featured"><a href="https://itunes.apple.com/us/app/i-wanna-san-francisco-food/id1009132577?mt=8" target="blank">Download</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div id="hero" class="static-header light clearfix">
        <div class="text-heading">
            <h1 class="animated hiding" data-animation="bounceInDown" data-delay="0"><span class="highlight">i wanna</span></h1>
            <p class="animated hiding" data-animation="fadeInDown" data-delay="500">Discover the best restaurants and bars in the San Francisco Bay Area without being overwhelmed by hundreds of options.</p>
            <a href="https://itunes.apple.com/us/app/i-wanna-san-francisco-food/id1009132577?mt=8" target="blank"><img src="../../../assets/Download_on_the_App_Store_Badge_US-UK_135x40.svg" class="app-download-button animated hiding" data-animation="bounceIn" data-delay="900"/></a>
            <ul class="list-inline">
            </ul>
        </div>
    </div>

    <hr class="no-margin" />

    <footer id="contact" class="footer light">
        <div class="container">
            <div class="footer-content row">
                <div class="col-sm-12">
                    <div class="footer-title footer-center">Contact</div>
                        <p class="thin footer-center">Say hello.</p>
                        <p class="thin footer-center-contact"><a href="mailto:contact@yeahiwanna.com">contact@yeahiwanna.com</a></p>
                </div>
            </div>
        </div>
    </footer>

    <div class="back-to-top"><i class="fa fa-angle-up fa-3x"></i></div>

    <script type="text/javascript" src="../../../assets/jquery-2.1.0.min.js"></script>
    <script type="text/javascript" src="../../../assets/bootstrap.min.js"></script>
    <script type="text/javascript" src="../../../assets/jquery.flexslider-min.js"></script>
    <script type="text/javascript" src="../../../assets/jquery.nav.js"></script>
    <script type="text/javascript" src="../../../assets/jquery.appear.js"></script>
    <script type="text/javascript" src="../../../assets/jquery.plugin.js"></script>
    <script type="text/javascript" src="../../../assets/jquery.countdown.js"></script>
    <script type="text/javascript" src="../../../assets/waypoints.min.js"></script>
    <script type="text/javascript" src="../../../assets/waypoints-sticky.min.js"></script>
    <script type="text/javascript" src="../../../assets/jquery.validate.js"></script>
    <script type="text/javascript" src="../../../assets/toastr.min.js"></script>
    <script type="text/javascript" src="../../../assets/headhesive.min.js"></script>
  <script type="text/javascript" src="../../../assets/mailchimp/mailing-list.js"></script>
    <script type="text/javascript" src="../../../assets/scripts.js"></script>
    <script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-63385529-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>